#!/usr/bin/env bash

# Year-specific WPICode defaults. CI may override repository paths while test
# builds still retain the same product identity.
WPICODE_YEAR="${WPICODE_YEAR:-2027}"
PRODUCT_NAME="${PRODUCT_NAME:-WPICode ${WPICODE_YEAR}}"
APP_NAME="${APP_NAME:-${PRODUCT_NAME}}"
ARCHIVE_NAME="${ARCHIVE_NAME:-WPICode-${WPICODE_YEAR}}"
BINARY_NAME="${BINARY_NAME:-wpicode-${WPICODE_YEAR}}"
ASSETS_REPOSITORY="${ASSETS_REPOSITORY:-wpilibsuite/wpicode}"
GH_REPO_PATH="${GH_REPO_PATH:-wpilibsuite/wpicode}"
ORG_NAME="${ORG_NAME:-WPILib}"
GLOBAL_DIRNAME="${GLOBAL_DIRNAME:-${BINARY_NAME}}"
TUNNEL_APP_NAME="${TUNNEL_APP_NAME:-${BINARY_NAME}-tunnel}"
VSCODE_QUALITY="${VSCODE_QUALITY:-stable}"

DISABLE_UPDATE="yes"
SHOULD_BUILD_APPIMAGE="no"
SHOULD_BUILD_CLI="no"
SHOULD_BUILD_DEB="no"
SHOULD_BUILD_DMG="no"
SHOULD_BUILD_EXE_SYS="no"
SHOULD_BUILD_EXE_USR="no"
SHOULD_BUILD_MSI="no"
SHOULD_BUILD_MSI_NOUP="no"
SHOULD_BUILD_REH="no"
SHOULD_BUILD_REH_WEB="no"
SHOULD_BUILD_RPM="no"
SHOULD_BUILD_SRC="no"
SHOULD_BUILD_TAR="yes"
SHOULD_BUILD_ZIP="yes"

export APP_NAME ARCHIVE_NAME ASSETS_REPOSITORY BINARY_NAME DISABLE_UPDATE
export GH_REPO_PATH GLOBAL_DIRNAME ORG_NAME PRODUCT_NAME TUNNEL_APP_NAME
export VSCODE_QUALITY WPICODE_YEAR
export SHOULD_BUILD_APPIMAGE SHOULD_BUILD_CLI SHOULD_BUILD_DEB SHOULD_BUILD_DMG
export SHOULD_BUILD_EXE_SYS SHOULD_BUILD_EXE_USR SHOULD_BUILD_MSI
export SHOULD_BUILD_MSI_NOUP SHOULD_BUILD_REH SHOULD_BUILD_REH_WEB
export SHOULD_BUILD_RPM SHOULD_BUILD_SRC SHOULD_BUILD_TAR SHOULD_BUILD_ZIP
